modLoader="javafml"
loaderVersion="[1,)"
license="Not specified"
[[mods]]
modId="flightblock"
version="${version}"
displayName="FlightBlock"
displayTest="IGNORE_ALL_VERSION"
description="Tiered timed flight target blocks"
[[dependencies.flightblock]]
modId="minecraft"
type="required"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
